## The basic maths for processing graph-structured data

In [8]:
import torch

### Adjacency Matrix with random values
`torch.rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor`

Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1). The shape of the tensor is defined by the variable argument **size**.

In [24]:
adjacencyMatrix = torch.rand(size = (3, 3))
print(adjacencyMatrix)

tensor([[0.6879, 0.7145, 0.5458],
        [0.6777, 0.8877, 0.7386],
        [0.7016, 0.5337, 0.3681]])


Update the `adjacencyMatrix` with 0 or 1 conditionally

In [35]:
adjacencyMatrix[adjacencyMatrix > 0.5] = 1
adjacencyMatrix[adjacencyMatrix <= 0.5] = 0
print("Adjacency Matrix =\n", adjacencyMatrix)

Adjacency Matrix =
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 0.]])


In [37]:
def calculateDegreeMatrix(adjacencyMatrix):
    return torch.diag(adjacencyMatrix.sum(dim = -1))

In [38]:
degreeMatrix = calculateDegreeMatrix(adjacencyMatrix)
print("Degree Matrix =\n", degreeMatrix)

Degree Matrix =
 tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 2.]])
