<a href="https://colab.research.google.com/github/zaedulislam/Graph_Neural_Networks/blob/main/GS_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Libraries

In [8]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx
import scipy

## Skeleton Graph

### Skeleton Edges

In [9]:
# neighbour_base = [(0, 1), (1, 2), (2, 3), (0, 4), (4, 5), (5, 6),
#                   (0, 7), (7, 8), (8, 9), (8, 10), (10, 11),
#                   (12, 11), (8, 13), (13, 14), (14, 15)]

neighbour_base = [(0, 1), (1, 2), (2, 3)]

### Creating skeleton graph

In [10]:
G = nx.Graph(neighbour_base)

### Adjacency matrix of skeleton (G)

In [11]:
A = nx.adjacency_matrix(G)
print(A)

  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 3)	1
  (3, 2)	1


In [12]:
A = A.todense()
print("Adjacency matrix representation of G:\n", A)

Adjacency matrix representation of G:
 [[0 1 0 0]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 1 0]]


In [ ]:
def normalize_adjacency_matrix(A):
    Dl = np.sum(A, 0)
    num_node = A.shape[0]
    Dn = np.zeros((num_node, num_node))
    
    for i in range(num_node):
        if Dl[i] > 0:
            Dn[i, i] = Dl[i]**(-1/2)
    
    DAD = np.dot(np.dot(Dn, A), Dn)

    return DAD

In [ ]:
beta = 0.2
DAD = beta * normalize_adjacency_matrix(A)

### Display Lower Triangular Matrix

In [ ]:
DAD_lower = np.tril(DAD)
print(DAD_lower)

### Display Upper Triangular Matrix

In [ ]:
DAD_upper = np.triu(DAD)
print(DAD)

### Check if lower triangular and upper triangular matrix are equal

In [ ]:
DAD_upper_transpose = DAD_upper.transpose()

if np.array_equal(DAD_lower, DAD_upper_transpose):
    print("lower triangular and upper triangular matrices are equal")