<a href="https://colab.research.google.com/github/zaedulislam/Graph_Neural_Networks/blob/main/GS_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Libraries

In [105]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx
import scipy

### Step 1: Create the adjacency matrix

In [106]:
A = np.array([[0, 1, 0, 1],
                [1, 0, 1, 0],
                [0, 1, 0, 1],
                [1, 0, 1, 0]])

print(A)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [107]:
def normalize_adjacency_matrix(adjacency_matrix):
    # Step 2: Calculate the degree matrix
    degree_matrix = np.diag(np.sum(adjacency_matrix, axis=1))
    print("degree_matrix:\n", degree_matrix)

    # Step 3: Compute the inverse square root of the degree matrix
    degree_matrix_inv_sqrt = np.diag(1 / np.sqrt(np.sum(adjacency_matrix, axis=1)))

    # Step 4: Compute the product of the inverse square root of the degree matrix and the adjacency matrix
    symmetric_normalized_adjacency_matrix = np.dot(degree_matrix_inv_sqrt, np.dot(adjacency_matrix, degree_matrix_inv_sqrt))

    # Step 5: Compute the product of the result obtained in step 4 and the inverse square root of the degree matrix again
    symmetric_normalized_adjacency_matrix = np.dot(degree_matrix_inv_sqrt, np.dot(symmetric_normalized_adjacency_matrix, degree_matrix_inv_sqrt))

    # Step 6: The resulting matrix is the symmetric normalized adjacency matrix
    
    return symmetric_normalized_adjacency_matrix

In [108]:
beta = 0.2
DAD = beta * normalize_adjacency_matrix(A)
print("DAD:\n", DAD)

degree_matrix:
 [[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]
DAD:
 [[0.   0.05 0.   0.05]
 [0.05 0.   0.05 0.  ]
 [0.   0.05 0.   0.05]
 [0.05 0.   0.05 0.  ]]


### Display Lower Triangular Matrix

In [109]:
DAD_lower = np.tril(DAD)
print(DAD_lower)

[[0.   0.   0.   0.  ]
 [0.05 0.   0.   0.  ]
 [0.   0.05 0.   0.  ]
 [0.05 0.   0.05 0.  ]]


### Display Upper Triangular Matrix

In [110]:
DAD_upper = np.triu(DAD)
print(DAD)

[[0.   0.05 0.   0.05]
 [0.05 0.   0.05 0.  ]
 [0.   0.05 0.   0.05]
 [0.05 0.   0.05 0.  ]]


### Check if lower triangular and upper triangular matrix are equal

In [111]:
DAD_upper_transpose = DAD_upper.transpose()

if np.array_equal(DAD_lower, DAD_upper_transpose):
    print("lower triangular and upper triangular matrices are equal")

lower triangular and upper triangular matrices are equal
